version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE} 
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --default_authentication_plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  java-app:
    container_name: java-app
    image: awabhassan/my-repo:bootcamp-mysql-master
    ports:
      - 8080:8080
    environment:
      - DB_USER=${MYSQL_USER}
      - DB_PWD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_SERVER=${DB_SERVER}
    depends_on:
      - mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8085:80
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} 
volumes:
  mysql-data:
    driver: local